repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff-format
      - id: ruff
        args: ["--fix"]

  - repo: local
    hooks:
      - id: basedpyright
        name: basedpyright (errors only)
        entry: uv run basedpyright --level=error
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: uv run pytest -q
        language: system
        pass_filenames: false
        stages: [commit]

default_stages: [commit]

