name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync project deps (if any)
        run: |
          uv sync --frozen --no-install-project || true

      - name: Ruff format (check)
        run: uv run ruff format --check

      - name: Ruff check (fix in CI to report diffs)
        run: uv run ruff check --fix

      - name: basedpyright (errors only)
        run: uv run basedpyright --level=error

      - name: Pytest
        run: uv run pytest -q

      - name: Pre-commit (as final gate)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files


